apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
        - name: bad
          image: demo-app:local
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
          # Inseguro a propósito: sin securityContext
